# Generated by Django 5.0.1 on 2024-01-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='kind',
            field=models.CharField(choices=[('excavator', 'Excavator'), ('concrete mixer', 'Concrete mixer'), ('bulldozer', 'Bulldozer'), ('crane', 'Crane'), ('jackhammer', 'Jackhammer'), ('drill', 'Drill'), ('scaffolding', 'Scaffolding'), ('concrete pump', 'Concrete pump'), ('chainsaw', 'Chainsaw'), ('angle grinder', 'Angle grinder')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
